version: "3.7"
services:
  unrealircd:
    build: 
      context: . 
      dockerfile: Dockerfile
      args:
        VER: latest
    image: docker-unrealircd6/unrealircd:latest
    volumes:
      - "/home/ircd:/ircd"
